### ISSUE TITLE
MathLink.jl

### ISSUE THREAD

**Issue by ioannisPApapadopoulos** [ioannisPApapadopoulos/SumSpaces.jl#5]
@dlfivefifty In order to use the Mathematica routines for the inverse Fourier Transform computations, I currently use the package MathLinks.jl. But this does not play nice with Github actions and auto-testing. In parcticular if I were to include it in the dependencies, then Github actions fails to even compile SumSpaces.jl. 

Is there a correct way to get around this and only load MathLinks.jl if it can?

**Comment by dlfivefifty** [comment]
This might help: https://github.com/JuliaPackaging/Requires.jl
